/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartGlobImage: typeof import('./src/components/Pages/ChartGlobImage/index.vue')['default']
    CollapseItem: typeof import('./src/components/Pages/ChartItemSetting/CollapseItem.vue')['default']
    ColorList: typeof import('./src/components/Pages/ThemeColorSelect/components/ColorList.vue')['default']
    DialogContent: typeof import('./src/components/Plugins/DialogContent/index.vue')['default']
    EchartsRendererSetting: typeof import('./src/components/Pages/ChartItemSetting/EchartsRendererSetting.vue')['default']
    EditorWorker: typeof import('./src/components/Pages/MonacoEditor/EditorWorker.vue')['default']
    Flipper: typeof import('./src/components/Pages/Flipper/index.vue')['default']
    GlobalSetting: typeof import('./src/components/Pages/ChartItemSetting/GlobalSetting.vue')['default']
    GlobalSettingPosition: typeof import('./src/components/Pages/ChartItemSetting/GlobalSettingPosition.vue')['default']
    GoAppProvider: typeof import('./src/components/GoAppProvider/index.vue')['default']
    GoIconify: typeof import('./src/components/GoIconify/index.vue')['default']
    GoJob: typeof import('./src/components/GoJob/index.vue')['default']
    GoLang: typeof import('./src/components/GoLang/index.vue')['default']
    GoLangSelect: typeof import('./src/components/GoLangSelect/index.vue')['default']
    GoLoading: typeof import('./src/components/GoLoading/index.vue')['default']
    GoReload: typeof import('./src/components/GoReload/index.vue')['default']
    GoSkeleton: typeof import('./src/components/GoSkeleton/index.vue')['default']
    GoSwitch: typeof import('./src/components/GoSwitch/index.vue')['default']
    GoSystemInfo: typeof import('./src/components/GoSystemInfo/index.vue')['default']
    GoSystemSet: typeof import('./src/components/GoSystemSet/index.vue')['default']
    GoThemeSelect: typeof import('./src/components/GoThemeSelect/index.vue')['default']
    GoUserInfo: typeof import('./src/components/GoUserInfo/index.vue')['default']
    I18n: typeof import('./src/components/I18n/index.vue')['default']
    Job: typeof import('./src/components/GoJob/Job/index.vue')['default']
    LoadingContent: typeof import('./src/components/Plugins/LoadingContent/index.vue')['default']
    LoadingSkeleton: typeof import('./src/components/GoLoading/LoadingSkeleton.vue')['default']
    MacOsControlBtn: typeof import('./src/components/Tips/MacOsControlBtn/index.vue')['default']
    MessageContent: typeof import('./src/components/Plugins/MessageContent/index.vue')['default']
    MonacoEditor: typeof import('./src/components/Pages/MonacoEditor/index.vue')['default']
    NameSetting: typeof import('./src/components/Pages/ChartItemSetting/NameSetting.vue')['default']
    PositionSetting: typeof import('./src/components/Pages/ChartItemSetting/PositionSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./src/components/Pages/ChartItemSetting/SettingItem.vue')['default']
    SettingItemBox: typeof import('./src/components/Pages/ChartItemSetting/SettingItemBox.vue')['default']
    SizeSetting: typeof import('./src/components/Pages/ChartItemSetting/SizeSetting.vue')['default']
    StylesSetting: typeof import('./src/components/Pages/ChartItemSetting/StylesSetting.vue')['default']
    ThemeColorSelect: typeof import('./src/components/Pages/ThemeColorSelect/index.vue')['default']
  }
}
