name: Build Vue App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'

    - name: Install Dependencies
      run: npm install && export NODE_OPTIONS=--max_old_space_size=4096 &&npm run build

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist.zip
        
    - name: Upload the Package to the Release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*
        asset_name: "dist-${{ github.event.release.tag_name }}.zip"
        extract_asset_download_url: true
  
         
