name: Build Vue App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get version
      id: get_version
      run: | 
        echo "Tag ref: $GITHUB_REF"
      
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'

    - name: Install Dependencies
      run: npm install && export NODE_OPTIONS=--max_old_space_size=4096 && npm run build

    - name: Print tag
      run: |
        echo "The tag is $GITHUB_REF_NAME"
      
    - name: Write version file
      run: sudo echo "Xplay ui:$GITHUB_REF_NAME" > ./dist/version.txt

    - name: Create zip file
      run: |
        zip -r ./dist-$GITHUB_REF_NAME.zip ./dist
      

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist.zip
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        files: dist.zip
  
         
